GET http://127.0.0.1:3000/
###

GET http://localhost:8080/
###
GET http://localhost:8080/api/pets/

###
POST http://localhost:8080/api/pets
Content-Type: application/json

{
    "name": "JonasABUDABIS",
    "dob": "2003-05-15",
    "clientEmail": "augintiniai@email.lt"
}

