POST http://127.0.0.1:3000/api/medications/createTable
###
GET  http://127.0.0.1:3000/api/medications
###
POST  http://127.0.0.1:3000/api/medications/insert
Content-Type: application/json

{
"name":"Allergy shot",
"description":"injection to prevent allergies"
}

###


